### ISSUE TITLE
latest master fails to run via docker container

### ISSUE THREAD

**Issue by krehm** [argonne-lcf/dlio_benchmark#117]
This morning I executed the following code based on the README.md instructions:

git clone https://github.com/argonne-lcf/dlio_benchmark
cd dlio_benchmark/
docker build -t dlio .
docker run -t dlio dlio_benchmark ++workload.workflow.generate_data=True

It fails almost immediately with:

[root@delphi-017 dlio_benchmark]# docker run -t dlio dlio_benchmark ++workload.workflow.generate_data=True
Traceback (most recent call last):
  File "/usr/local/bin/dlio_benchmark", line 5, in <module>
    from dlio_benchmark.main import main
  File "/usr/local/lib/python3.8/dist-packages/dlio_benchmark/main.py", line 41, in <module>
    from dlio_benchmark.utils.statscounter import StatsCounter
  File "/usr/local/lib/python3.8/dist-packages/dlio_benchmark/utils/statscounter.py", line 18, in <module>
    from dlio_benchmark.utils.config import ConfigArguments
  File "/usr/local/lib/python3.8/dist-packages/dlio_benchmark/utils/config.py", line 35, in <module>
    from dlio_profiler.logger import fn_interceptor as Profile
  File "/usr/local/lib/python3.8/dist-packages/dlio_profiler/logger.py", line 19, in <module>
    import dlio_profiler_py as profiler
ModuleNotFoundError: No module named 'dlio_profiler_py'

**Comment by hariharan-devarajan** [comment]
@krehm can u share the build log. In the dev branch, the dlio-profiler was made required and not optional. seems like something failed during building of the container.

**Comment by krehm** [comment]
Here is what I did, I will follow in next post with the build log.

```
[root@delphi-017 dlio_benchmark]# pwd
/root/rehm/dlio_benchmark
[root@delphi-017 dlio_benchmark]# git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.README.md.swp

nothing added to commit but untracked files present (use "git add" to track)
[root@delphi-017 dlio_benchmark]# cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/argonne-lcf/dlio_benchmark.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
[root@delphi-017 dlio_benchmark]# docker build -t dlio . > build.log 2>&1
[root@delphi-017 dlio_benchmark]# docker run -t dlio dlio_benchmark ++workload.workflow.generate_data=True
Traceback (most recent call last):
  File "/usr/local/bin/dlio_benchmark", line 5, in <module>
    from dlio_benchmark.main import main
  File "/usr/local/lib/python3.8/dist-packages/dlio_benchmark/main.py", line 41, in <module>
    from dlio_benchmark.utils.statscounter import StatsCounter
  File "/usr/local/lib/python3.8/dist-packages/dlio_benchmark/utils/statscounter.py", line 18, in <module>
    from dlio_benchmark.utils.config import ConfigArguments
  File "/usr/local/lib/python3.8/dist-packages/dlio_benchmark/utils/config.py", line 35, in <module>
    from dlio_profiler.logger import fn_interceptor as Profile
  File "/usr/local/lib/python3.8/dist-packages/dlio_profiler/logger.py", line 19, in <module>
    import dlio_profiler_py as profiler
ModuleNotFoundError: No module named 'dlio_profiler_py'

[root@delphi-017 dlio_benchmark]#
```

**Comment by krehm** [comment]
[build.log](https://github.com/argonne-lcf/dlio_benchmark/files/13530991/build.log)

**Comment by krehm** [comment]
Yes, works fine now, thanks.
