### ISSUE TITLE
Issues with Cosmoflow when running it through MLPerf Storage v1.0

### ISSUE THREAD

**Issue by sakib-samar** [argonne-lcf/dlio_benchmark#173]
I am seeing this error after epoch 1 is completed on Cosmoflow. For context, I am running this code through the MLPerf Storage v1.0 branch.

Once epoch 1 completes, it errors out at the start of epoch 2. I have verified that this a recurring issue using both H100 and A100 GPUs.

```
[INFO] 2024-03-15T17:31:15.297461 Ending epoch 1 - 237023 steps completed in 1454.49 s [/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/utils/statscounter.py:159]
Error executing job with overrides: ['workload=cosmoflow_h100', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.dataset.num_files_train=1896187', '++workload.workflow.profiling=False', '++workload
.profiling.profiler=none']
Error executing job with overrides: ['workload=cosmoflow_h100', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.dataset.num_files_train=1896187', '++workload.workflow.profiling=False', '++workload
.profiling.profiler=none']
Error executing job with overrides: ['workload=cosmoflow_h100', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.dataset.num_files_train=1896187', '++workload.workflow.profiling=False', '++workload
.profiling.profiler=none']
Error executing job with overrides: ['workload=cosmoflow_h100', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.dataset.num_files_train=1896187', '++workload.workflow.profiling=False', '++workload
.profiling.profiler=none']
Error executing job with overrides: ['workload=cosmoflow_h100', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.dataset.num_files_train=1896187', '++workload.workflow.profiling=False', '++workload
.profiling.profiler=none']
[INFO] 2024-03-15T17:31:15.298171 Starting epoch 2: 237023 steps expected [/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/utils/statscounter.py:128]
Error executing job with overrides: ['workload=cosmoflow_h100', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.dataset.num_files_train=1896187', '++workload.workflow.profiling=False', '++workload
.profiling.profiler=none']
[INFO] 2024-03-15T17:31:15.298319 Starting block 1 [/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/utils/statscounter.py:198]
Error executing job with overrides: ['workload=cosmoflow_h100', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.dataset.num_files_train=1896187', '++workload.workflow.profiling=False', '++workload
.profiling.profiler=none']
Error executing job with overrides: ['workload=cosmoflow_h100', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.dataset.num_files_train=1896187', '++workload.workflow.profiling=False', '++workload
.profiling.profiler=none']
Traceback (most recent call last):
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/data_loader/dali_data_loader.py", line 116, in next
    outputs = pipe.share_outputs()
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/nvidia/dali/pipeline.py", line 1132, in share_outputs
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/data_loader/dali_data_loader.py", line 116, in next
    outputs = pipe.share_outputs()
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/nvidia/dali/pipeline.py", line 1132, in share_outputs
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):                                                                                                                                                                                                 [120/1990]
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/main.py", line 396, in main
    benchmark.run()
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/dlio_profiler/logger.py", line 183, in wrapper
    x = func(*args, **kwargs)
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/main.py", line 343, in run
    steps = self._train(epoch)
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/main.py", line 396, in main
    benchmark.run()
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/dlio_profiler/logger.py", line 183, in wrapper
    x = func(*args, **kwargs)
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/main.py", line 343, in run
    steps = self._train(epoch)
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/dlio_profiler/logger.py", line 183, in wrapper
    x = func(*args, **kwargs)
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/main.py", line 264, in _train
    for batch in dlp.iter(loader.next()):
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/dlio_profiler/logger.py", line 203, in iter
    for v in func:
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/dlio_profiler/logger.py", line 183, in wrapper
    x = func(*args, **kwargs)
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/main.py", line 264, in _train
    for batch in dlp.iter(loader.next()):
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/dlio_profiler/logger.py", line 203, in iter
    for v in func:
RuntimeError: generator raised StopIteration
RuntimeError: generator raised StopIteration

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/data_loader/dali_data_loader.py", line 116, in next
    outputs = pipe.share_outputs()
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/nvidia/dali/pipeline.py", line 1132, in share_outputs
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/main.py", line 396, in main
    benchmark.run()
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/dlio_profiler/logger.py", line 183, in wrapper
    x = func(*args, **kwargs)
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/main.py", line 343, in run
    steps = self._train(epoch)
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/dlio_profiler/logger.py", line 183, in wrapper
    x = func(*args, **kwargs)
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/main.py", line 264, in _train
    for batch in dlp.iter(loader.next()):
Traceback (most recent call last):
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/dlio_profiler/logger.py", line 203, in iter
    for v in func:
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "/e1000/ssamar/flash/mlperf_storage_v1/storage/dlio_benchmark/dlio_benchmark/data_loader/dali_data_loader.py", line 116, in next
    outputs = pipe.share_outputs()
  File "/cstor/ssamar/miniconda3/envs/mlperf3/lib/python3.9/site-packages/nvidia/dali/pipeline.py", line 1132, in share_outputs
    raise StopIteration
```

**Comment by zhenghh04** [comment]
You don't have to generate the dataset again.
