### ISSUE TITLE
ValueError: batch_size=None option disables auto-batching and is mutually exclusive with drop_last

### ISSUE THREAD

**Issue by arcturus5340** [argonne-lcf/dlio_benchmark#180]
When running the code from the [documentation page](https://dlio-benchmark.readthedocs.io/en/latest/run.html#running-benchmark), I encountered the following problem:
```
[INFO] 2024-04-05T14:33:09.147860 Running DLIO with 8 process(es) [/home/dlio_benchmark/src/dlio_benchmark.py:102]
[INFO] 2024-04-05T14:33:09.148168 Reading YAML config file './configs/workload/unet3d.yaml' [/home/dlio_benchmark/src/dlio_benchmark.py:104]
[INFO] 2024-04-05T14:33:09.154013 Profiling Started with iostat [/home/dlio_benchmark/src/dlio_benchmark.py:185]
[INFO] 2024-04-05T14:33:10.030432 Max steps per epoch: 5 = 1 * 168 / 4 / 8 (samples per file * num files / batch size / comm size) [/home/dlio_benchmark/src/dlio_benchmark.py:308]
[INFO] 2024-04-05T14:33:10.030912 Steps per eval: 0 = 1 * 0 / 1 / 8 (samples per file * num files / batch size eval / comm size) [/home/dlio_benchmark/src/dlio_benchmark.py:312]
[INFO] 2024-04-05T14:33:10.031058 Starting epoch 1: 5 steps expected [/home/dlio_benchmark/src/utils/statscounter.py:65]
[INFO] 2024-04-05T14:33:10.031686 Prefetch size is 0; a default prefetch factor of 2 will be set to Torch DataLoader. [/home/dlio_benchmark/src/reader/torch_data_loader_reader.py:123]
[INFO] 2024-04-05T14:33:10.033088 Starting block 1 [/home/dlio_benchmark/src/utils/statscounter.py:107]
[INFO] 2024-04-05T14:33:52.285991 Rank 5 step 1 processed 4 samples in 42.25287222862244 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:33:52.286127 Rank 0 step 1 processed 4 samples in 42.25265336036682 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:33:52.286025 Rank 6 step 1 processed 4 samples in 42.25288677215576 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:33:52.286107 Rank 1 step 1 processed 4 samples in 42.25290298461914 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:33:52.286141 Rank 2 step 1 processed 4 samples in 42.252936124801636 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:33:52.286113 Rank 3 step 1 processed 4 samples in 42.25290322303772 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:33:52.286108 Rank 4 step 1 processed 4 samples in 42.25290322303772 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:33:52.286117 Rank 7 step 1 processed 4 samples in 42.252907276153564 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:40.404293 Rank 4 step 2 processed 4 samples in 48.11696195602417 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:40.404411 Rank 0 step 2 processed 4 samples in 48.11718225479126 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:40.404406 Rank 1 step 2 processed 4 samples in 48.11705923080444 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:40.404418 Rank 2 step 2 processed 4 samples in 48.117016077041626 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:40.404414 Rank 3 step 2 processed 4 samples in 48.11704182624817 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:40.404404 Rank 5 step 2 processed 4 samples in 48.117244243621826 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:40.404415 Rank 6 step 2 processed 4 samples in 48.11717414855957 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:40.404418 Rank 7 step 2 processed 4 samples in 48.11697769165039 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:41.773245 Rank 0 step 3 processed 4 samples in 1.3680288791656494 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:41.773245 Rank 1 step 3 processed 4 samples in 1.3680779933929443 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:41.773245 Rank 2 step 3 processed 4 samples in 1.3680636882781982 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:41.773245 Rank 3 step 3 processed 4 samples in 1.3680734634399414 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:41.773245 Rank 4 step 3 processed 4 samples in 1.3684496879577637 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:41.773244 Rank 5 step 3 processed 4 samples in 1.3680462837219238 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:41.773246 Rank 6 step 3 processed 4 samples in 1.3680644035339355 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:41.773247 Rank 7 step 3 processed 4 samples in 1.3680729866027832 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:43.136428 Rank 2 step 4 processed 4 samples in 1.3628950119018555 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:43.136428 Rank 3 step 4 processed 4 samples in 1.362884759902954 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:43.136428 Rank 6 step 4 processed 4 samples in 1.362865686416626 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:43.136428 Rank 7 step 4 processed 4 samples in 1.3628854751586914 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:43.136428 Rank 0 step 4 processed 4 samples in 1.3628740310668945 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:43.136430 Rank 1 step 4 processed 4 samples in 1.3628816604614258 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:43.136428 Rank 4 step 4 processed 4 samples in 1.362868309020996 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:43.136427 Rank 5 step 4 processed 4 samples in 1.3628768920898438 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:44.502589 Rank 4 step 5 processed 4 samples in 1.3658692836761475 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:44.502589 Rank 5 step 5 processed 4 samples in 1.3658723831176758 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:44.502592 Rank 6 step 5 processed 4 samples in 1.3658771514892578 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:44.502591 Rank 0 step 5 processed 4 samples in 1.3658645153045654 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:44.502591 Rank 1 step 5 processed 4 samples in 1.3658671379089355 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:44.502592 Rank 2 step 5 processed 4 samples in 1.3658878803253174 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:44.502607 Rank 3 step 5 processed 4 samples in 1.365903615951538 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:44.502595 Rank 7 step 5 processed 4 samples in 1.3658838272094727 s [/home/dlio_benchmark/src/utils/statscounter.py:161]
[INFO] 2024-04-05T14:34:44.502887 Maximum number of steps reached [/home/dlio_benchmark/src/dlio_benchmark.py:276]
[INFO] 2024-04-05T14:34:44.503073 Ending block 1 - 5 steps completed in 94.47 s [/home/dlio_benchmark/src/utils/statscounter.py:122]
[INFO] 2024-04-05T14:34:44.624797 Epoch 1 [training] accelerator_under_utilization: 12.90641484320847 [/home/dlio_benchmark/src/dlio_benchmark.py:294]
[INFO] 2024-04-05T14:34:44.625346 Ending epoch 1 - 5 steps completed in 94.59 s [/home/dlio_benchmark/src/utils/statscounter.py:83]
[INFO] 2024-04-05T14:34:44.632536 Starting eval - 0 steps expected [/home/dlio_benchmark/src/utils/statscounter.py:88]
[INFO] 2024-04-05T14:34:44.632878 Prefetch size is 0; a default prefetch factor of 2 will be set to Torch DataLoader. [/home/dlio_benchmark/src/reader/torch_data_loader_reader.py:123]
Error executing job with overrides: ['workload=unet3d', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.workflow.evaluation=True']
Error executing job with overrides: ['workload=unet3d', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.workflow.evaluation=True']
Error executing job with overrides: ['workload=unet3d', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.workflow.evaluation=True']
Error executing job with overrides: ['workload=unet3d', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.workflow.evaluation=True']
Error executing job with overrides: ['workload=unet3d', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.workflow.evaluation=True']
Error executing job with overrides: ['workload=unet3d', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.workflow.evaluation=True']
Error executing job with overrides: ['workload=unet3d', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.workflow.evaluation=True']
Error executing job with overrides: ['workload=unet3d', '++workload.workflow.generate_data=False', '++workload.workflow.train=True', '++workload.workflow.evaluation=True']
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 391, in main
    benchmark.run()
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 342, in run
    self.framework.get_reader(DatasetType.VALID).read(epoch)
  File "/home/dlio_benchmark/src/reader/torch_data_loader_reader.py", line 124, in read
    self._dataset = DataLoader(dataset,
  File "/home/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 335, in __init__
    raise ValueError('batch_size=None option disables auto-batching '
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 391, in main
    benchmark.run()
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 342, in run
    self.framework.get_reader(DatasetType.VALID).read(epoch)
  File "/home/dlio_benchmark/src/reader/torch_data_loader_reader.py", line 124, in read
    self._dataset = DataLoader(dataset,
  File "/home/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 335, in __init__
    raise ValueError('batch_size=None option disables auto-batching '
ValueError: batch_size=None option disables auto-batching and is mutually exclusive with drop_last

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
ValueError: batch_size=None option disables auto-batching and is mutually exclusive with drop_last

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 391, in main
    benchmark.run()
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 342, in run
    self.framework.get_reader(DatasetType.VALID).read(epoch)
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 391, in main
    benchmark.run()
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 342, in run
    self.framework.get_reader(DatasetType.VALID).read(epoch)
  File "/home/dlio_benchmark/src/reader/torch_data_loader_reader.py", line 124, in read
    self._dataset = DataLoader(dataset,
  File "/home/dlio_benchmark/src/reader/torch_data_loader_reader.py", line 124, in read
    self._dataset = DataLoader(dataset,
  File "/home/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 335, in __init__
    raise ValueError('batch_size=None option disables auto-batching '
  File "/home/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 335, in __init__
    raise ValueError('batch_size=None option disables auto-batching '
Traceback (most recent call last):
ValueError: batch_size=None option disables auto-batching and is mutually exclusive with drop_last

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
ValueError: batch_size=None option disables auto-batching and is mutually exclusive with drop_last

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 391, in main
    benchmark.run()
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 342, in run
    self.framework.get_reader(DatasetType.VALID).read(epoch)
  File "/home/dlio_benchmark/src/reader/torch_data_loader_reader.py", line 124, in read
    self._dataset = DataLoader(dataset,
  File "/home/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 335, in __init__
    raise ValueError('batch_size=None option disables auto-batching '
Traceback (most recent call last):
ValueError: batch_size=None option disables auto-batching and is mutually exclusive with drop_last

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 391, in main
    benchmark.run()
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 342, in run
    self.framework.get_reader(DatasetType.VALID).read(epoch)
  File "/home/dlio_benchmark/src/reader/torch_data_loader_reader.py", line 124, in read
    self._dataset = DataLoader(dataset,
  File "/home/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 335, in __init__
    raise ValueError('batch_size=None option disables auto-batching '
ValueError: batch_size=None option disables auto-batching and is mutually exclusive with drop_last

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 391, in main
    benchmark.run()
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 342, in run
    self.framework.get_reader(DatasetType.VALID).read(epoch)
  File "/home/dlio_benchmark/src/reader/torch_data_loader_reader.py", line 124, in read
    self._dataset = DataLoader(dataset,
  File "/home/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 335, in __init__
    raise ValueError('batch_size=None option disables auto-batching '
ValueError: batch_size=None option disables auto-batching and is mutually exclusive with drop_last

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 391, in main
    benchmark.run()
  File "/home/dlio_benchmark/src/dlio_benchmark.py", line 342, in run
    self.framework.get_reader(DatasetType.VALID).read(epoch)
  File "/home/dlio_benchmark/src/reader/torch_data_loader_reader.py", line 124, in read
    self._dataset = DataLoader(dataset,
  File "/home/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 335, in __init__
    raise ValueError('batch_size=None option disables auto-batching '
ValueError: batch_size=None option disables auto-batching and is mutually exclusive with drop_last

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
This seems to be a consequence of initialising the DataLoader with batch_size=None and drop_last=True, which causes an error in pytorch ([here is the source code leading to the exception](https://github.com/pytorch/pytorch/blob/cfd06bd60cc959622292112ba535a2aadc58f7c7/torch/utils/data/dataloader.py#L338)). I'm using dlio v1.1 at startup, how do I get around this problem?

**Comment by arcturus5340** [comment]
The problem has been solved in the latest version.
