### ISSUE TITLE
Negative computation time when stdev of computation time is provided

### ISSUE THREAD

**Issue by rayandrew** [argonne-lcf/dlio_benchmark#232]
Hi @zhenghh04 and @hariharan-devarajan,

I encountered error when providing stdev in the configuration.

We can fix it by adding the `abs` while calling `random.normal` in `main.py`

```diff
[INFO] Computation time is: 1.2056848216668536 [/lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/dlio_benchmark/main.py:271]
+ [INFO] Computation time is: -0.22297661682373804 [/lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/dlio_benchmark/main.py:271]
[INFO] Computation time is: 0.7074011037224097 [/lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/dlio_benchmark/main.py:271]
[INFO] Computation time is: 0.5691646364965793 [/lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/dlio_benchmark/main.py:271]
Error executing job with overrides: ['workload=stormer_a100']
Traceback (most recent call last):
  File "/lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/dlio_benchmark/main.py", line 387, in run_benchmark
    benchmark.run()
  File "/lus/eagle/projects/MDClimSim/rayandrew/venvs/dlio-benchmark/lib/python3.11/site-packages/dftracer/logger.py", line 214, in wrapper
    x = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/dlio_benchmark/main.py", line 339, in run
    steps = self._train(epoch)
            ^^^^^^^^^^^^^^^^^^
  File "/lus/eagle/projects/MDClimSim/rayandrew/venvs/dlio-benchmark/lib/python3.11/site-packages/dftracer/logger.py", line 214, in wrapper
    x = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/dlio_benchmark/main.py", line 272, in _train
    self.framework.compute(batch, epoch, block_step, computation_time)
  File "/lus/eagle/projects/MDClimSim/rayandrew/venvs/dlio-benchmark/lib/python3.11/site-packages/dftracer/logger.py", line 214, in wrapper
    x = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/dlio_benchmark/framework/torch_framework.py", line 96, in compute
    torch_sleep(computation_time)
  File "/lus/eagle/projects/MDClimSim/rayandrew/dlio-benchmark/dlio_benchmark/framework/torch_framework.py", line 53, in torch_sleep
    return sleep(sleep_time)
           ^^^^^^^^^^^^^^^^^
ValueError: sleep length must be non-negative
```

**Comment by rayandrew** [comment]
Simple reproducible code

```python
from numpy import random

avg = 0.789605
stdev = 0.341226

count = 0
for i in range(10000):
    if random.normal(avg, stdev) < 0: 
        count += 1

print(count)
```
