### ISSUE TITLE
dlio_postprocessor.py fails extracting iostat trace

### ISSUE THREAD

**Issue by karanveersingh5623** [argonne-lcf/dlio_benchmark#28]
Hi Team

Below is my run config . Using default.yaml template and changing some params

MPI_procs = 128

batch_size=64
epochs = 2

profiling: 
  profiler: iostat
  iostat_devices: nvme3n1

Below is the failing trace 

```
2022-12-20 06:42:29 Processing loading and processing times for epoch 1
2022-12-20 06:42:29 Processing loading times for phase eval
2022-12-20 06:42:29 Processing processing times for phase eval
2022-12-20 06:42:29 Processing loading and processing times for epoch 2
2022-12-20 06:42:29 Reading from /workspace/dlio/hydra_log/default/2022-12-20-06-42-17/125_load_and_proc_times.json
2022-12-20 06:42:29 Processing loading and processing times for epoch 1
2022-12-20 06:42:29 Processing loading times for phase eval
2022-12-20 06:42:29 Processing processing times for phase eval
2022-12-20 06:42:29 Processing loading and processing times for epoch 2
2022-12-20 06:42:29 Reading from /workspace/dlio/hydra_log/default/2022-12-20-06-42-17/126_load_and_proc_times.json
2022-12-20 06:42:29 Processing loading and processing times for epoch 1
2022-12-20 06:42:29 Processing loading times for phase eval
2022-12-20 06:42:29 Processing processing times for phase eval
2022-12-20 06:42:29 Processing loading and processing times for epoch 2
2022-12-20 06:42:29 Reading from /workspace/dlio/hydra_log/default/2022-12-20-06-42-17/127_load_and_proc_times.json
2022-12-20 06:42:29 Processing loading and processing times for epoch 1
2022-12-20 06:42:29 Processing loading times for phase eval
2022-12-20 06:42:29 Processing processing times for phase eval
2022-12-20 06:42:29 Processing loading and processing times for epoch 2
2022-12-20 06:42:29 Computing overall stats
2022-12-20 06:42:29 Computing per epoch stats
2022-12-20 06:42:29 Computing stats for epoch 1 eval
2022-12-20 06:42:29 Parsing iostat trace
2022-12-20 06:42:29 Processing iostat item 0
2022-12-20 06:42:29 Extracting stats from iostat trace
2022-12-20 06:42:29 Extracting stats for epoch 1 start
2022-12-20 06:42:29 Extracting stats for epoch 1 block1
===============Processing DLIO output================
  Job configuration
  output_folder: /workspace/dlio/hydra_log/default/2022-12-20-06-42-17
  num_proc: 128
  epochs: 2
Traceback (most recent call last):
  File "/workspace/dlio/src/dlio_postprocessor.py", line 626, in <module>
  batch_size: 64
  do_eval: True
  batch_size_eval: 1
  do_checkpoint: False
  debug: False
  name: default
    main()
  File "/workspace/dlio/src/dlio_postprocessor.py", line 623, in main
    postproc.generate_report()
  File "/workspace/dlio/src/dlio_postprocessor.py", line 552, in generate_report
    self.extract_stats_from_iostat_trace()
  File "/workspace/dlio/src/dlio_postprocessor.py", line 346, in extract_stats_from_iostat_trace
    start, end = pd.to_datetime(phase_data['start']), pd.to_datetime(phase_data['end'])
KeyError: 'end'
```

**Comment by karanveersingh5623** [comment]
@zhenghh04  , when I run dlio using 64 MPI processes , the same config runs fine .
please refer **num_proc** 

```
2022-12-20 06:55:58 Reading from /workspace/dlio/hydra_log/default/2022-12-20-06-55-46/62_load_and_proc_times.json                                                                                      [5/1463]
2022-12-20 06:55:58 Processing loading and processing times for epoch 1
2022-12-20 06:55:58 Processing loading times for phase block1
2022-12-20 06:55:58 Processing loading times for phase eval
2022-12-20 06:55:58 Processing processing times for phase block1
2022-12-20 06:55:58 Processing processing times for phase eval
2022-12-20 06:55:58 Processing loading and processing times for epoch 2
2022-12-20 06:55:58 Processing loading times for phase block1
2022-12-20 06:55:58 Processing processing times for phase block1
2022-12-20 06:55:58 Reading from /workspace/dlio/hydra_log/default/2022-12-20-06-55-46/63_load_and_proc_times.json
2022-12-20 06:55:58 Processing loading and processing times for epoch 1
2022-12-20 06:55:58 Processing loading times for phase block1
2022-12-20 06:55:58 Processing loading times for phase eval
2022-12-20 06:55:58 Processing processing times for phase block1
2022-12-20 06:55:58 Processing processing times for phase eval
2022-12-20 06:55:58 Processing loading and processing times for epoch 2
2022-12-20 06:55:58 Processing loading times for phase block1
2022-12-20 06:55:58 Processing processing times for phase block1
2022-12-20 06:55:58 Computing overall stats
2022-12-20 06:55:58 Computing per epoch stats
2022-12-20 06:55:58 Computing stats for epoch 1 block1
2022-12-20 06:55:58 Computing stats for epoch 1 eval
2022-12-20 06:55:58 Computing stats for epoch 2 block1
2022-12-20 06:55:58 Parsing iostat trace
2022-12-20 06:55:58 Processing iostat item 0
2022-12-20 06:55:58 Extracting stats from iostat trace
2022-12-20 06:55:58 Extracting stats for epoch 1 start
2022-12-20 06:55:58 Extracting stats for epoch 1 block1
2022-12-20 06:55:58 Extracting stats for epoch 1 end
2022-12-20 06:55:58 Extracting stats for epoch 1 duration
2022-12-20 06:55:58 Extracting stats for epoch 1 eval
2022-12-20 06:55:58 Less than 2 data points for rMB/s
2022-12-20 06:55:58 Less than 2 data points for wMB/s
2022-12-20 06:55:58 Less than 2 data points for r/s
2022-12-20 06:55:58 Less than 2 data points for w/s
2022-12-20 06:55:58 Less than 2 data points for r_await
2022-12-20 06:55:58 Less than 2 data points for w_await
2022-12-20 06:55:58 Less than 2 data points for aqu-sz
2022-12-20 06:55:58 Less than 2 data points for user
2022-12-20 06:55:58 Less than 2 data points for system
2022-12-20 06:55:58 Less than 2 data points for iowait
2022-12-20 06:55:58 Less than 2 data points for steal
2022-12-20 06:55:58 Less than 2 data points for idle
2022-12-20 06:55:58 Extracting stats for epoch 2 start
2022-12-20 06:55:58 Extracting stats for epoch 2 block1
2022-12-20 06:55:58 Extracting stats for epoch 2 end
2022-12-20 06:55:58 Extracting stats for epoch 2 duration
2022-12-20 06:55:58 Writing report
2022-12-20 06:55:58 Successfully wrote /workspace/dlio/hydra_log/default/2022-12-20-06-55-46/DLIO_default_report.txt
===============Processing DLIO output================
  Job configuration
  output_folder: /workspace/dlio/hydra_log/default/2022-12-20-06-55-46
  num_proc: 64
  epochs: 2
  batch_size: 64
  do_eval: True

```
