### ISSUE TITLE
Building horovod requires gcc version < 8

### ISSUE THREAD

**Issue by jovonho** [argonne-lcf/dlio_benchmark#5]
I am trying to build DLIO in a virtual environment to test its portability but I cannot build horovod.
I get the following error indicating that the gcc version on my machine is not supported. 
I could downgrade gcc, however this is a shared system and it might break other things.

Maybe we should go back to using docker, to increase portability, unless we are supposed to be using docker? In this case, we should say it in the readme.

```
Failed to build horovod
Installing collected packages: horovod
  Running setup.py install for horovod ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for horovod did not run successfully.
  │ exit code: 1
  ╰─> [278 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/horovod
(... skipped)
      Running CMake in build/temp.linux-x86_64-3.8/RelWithDebInfo:
      cmake /tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE:FILEPATH=/dl-bench/lhovon/dlio_benchmark/.venv/bin/python3
      cmake --build . --config RelWithDebInfo -- -j8 VERBOSE=1
      -- Could not find CCache. Consider installing CCache to speed up compilation.
      -- The CXX compiler identification is GNU 9.4.0
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Build architecture flags: -mf16c -mavx -mfma
      -- Using command /dl-bench/lhovon/dlio_benchmark/.venv/bin/python3
      -- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
      -- Found MPI: TRUE (found version "3.1")
      -- Looking for a CUDA compiler
      -- Looking for a CUDA compiler - /usr/bin/nvcc
      -- Looking for a CUDA host compiler - /usr/bin/c++
      -- The CUDA compiler identification is unknown
      -- Check for working CUDA compiler: /usr/bin/nvcc
      -- Check for working CUDA compiler: /usr/bin/nvcc -- broken
      CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCUDACompiler.cmake:46 (message):
        The CUDA compiler
      
          "/usr/bin/nvcc"
      
        is not able to compile a simple test program.
      
        It fails with the following output:
      
          Change Dir: /tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/build/temp.linux-x86_64-3.8/RelWithDebInfo/CMakeFiles/CMakeTmp
      
          Run Build Command(s):/usr/bin/make cmTC_a113d/fast && /usr/bin/make -f CMakeFiles/cmTC_a113d.dir/build.make CMakeFiles/cmTC_a113d.dir/build
          make[1]: Entering directory '/tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/build/temp.linux-x86_64-3.8/RelWithDebInfo/CMakeFiles/CMakeTmp'
          Building CUDA object CMakeFiles/cmTC_a113d.dir/main.cu.o
          /usr/bin/nvcc -ccbin=/usr/bin/c++    -x cu -c /tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/build/temp.linux-x86_64-3.8/RelWithDebInfo/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_a113d.dir/main.cu.o
          In file included from /usr/include/cuda_runtime.h:83,
                           from <command-line>:
          /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
            138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
                |  ^~~~~
          make[1]: *** [CMakeFiles/cmTC_a113d.dir/build.make:66: CMakeFiles/cmTC_a113d.dir/main.cu.o] Error 1
          make[1]: Leaving directory '/tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/build/temp.linux-x86_64-3.8/RelWithDebInfo/CMakeFiles/CMakeTmp'
          make: *** [Makefile:121: cmTC_a113d/fast] Error 2
      
      
      
      
      
        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:177 (enable_language)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/build/temp.linux-x86_64-3.8/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/build/temp.linux-x86_64-3.8/RelWithDebInfo/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/setup.py", line 213, in <module>
          setup(name='horovod',
        File "/dl-bench/lhovon/dlio_benchmark/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/dl-bench/lhovon/dlio_benchmark/.venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
          self.run_command('build')
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/dl-bench/lhovon/dlio_benchmark/.venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/setup.py", line 145, in build_extensions
          subprocess.check_call(command, cwd=cmake_build_dir)
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-install-7kh3ez0t/horovod_b725b0ff4af74068b022383e3db12517/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE:FILEPATH=/dl-bench/lhovon/dlio_benchmark/.venv/bin/python3']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> horovod

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by zhenghh04** [comment]
Horovod is not easy to build. 

For DLIO, it really does not matter whether we have Horovod, DDP or other communication libraries, such as NCCL, CCL. We only use Barrier(). So I removed the dependency on Horovod, and use only mpi4py.
